name: deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm ci
      - name: Copy build to the server
        uses: appleboy/scp-action@master
        with:
          host: 82.148.19.60
          username: deployer
          key: ${{ secrets.DEPLOY_KEY }}
          source: "src,node_modules"
          target: "/home/deployer/crawler"
          rm: true
      - name: "Run app"
        uses: appleboy/ssh-action@master
        with:
          host: 82.148.19.60
          username: deployer
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd crawler
            touch .env
            echo "PORT=8888" >> .env
            npm i puppeteer
            pm2 restart crawler
